services:

  # User Preference Microservice
  - type: pserv
    name: allermind-userpreference
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./userpreference-microservice/Dockerfile
    dockerContext: ./userpreference-microservice
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: DB_HOST
        fromDatabase:
          name: allermind-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: allermind-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: allermind-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: allermind-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: allermind-db
          property: password
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    disk:
      name: userpreference-data
      mountPath: /app/data
      sizeGB: 1

  # Weather Air Pollution Microservice
  - type: pserv
    name: allermind-weather
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./weather-airpollution-microservice/Dockerfile
    dockerContext: ./weather-airpollution-microservice
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: DB_HOST
        fromDatabase:
          name: allermind-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: allermind-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: allermind-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: allermind-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: allermind-db
          property: password
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m

  # Pollen Microservice
  - type: pserv
    name: allermind-pollen
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./pollen-microservice/Dockerfile
    dockerContext: ./pollen-microservice
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: DB_HOST
        fromDatabase:
          name: allermind-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: allermind-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: allermind-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: allermind-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: allermind-db
          property: password
      - key: GOOGLE_POLLEN_API_KEY
        sync: false
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m

  # ML Model Microservice (Python)
  - type: pserv
    name: allermind-ml-model
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./ml-model-microservice/Dockerfile
    dockerContext: ./ml-model-microservice
    envVars:
      - key: FLASK_APP
        value: real_model_test.py
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHON_ENV
        value: production

  # Model Microservice (Orchestrator)
  - type: pserv
    name: allermind-model
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./model-microservice/Dockerfile
    dockerContext: ./model-microservice
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: POLLEN_SERVICE_BASE_URL
        value: http://allermind-pollen:10000
      - key: WEATHER_SERVICE_BASE_URL
        value: http://allermind-weather:10000
      - key: ML_MODEL_SERVICE_BASE_URL
        value: http://allermind-ml-model:10000
      - key: USER_PREFERENCE_SERVICE_BASE_URL
        value: http://allermind-userpreference:10000
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m

  # Flutter Web Application
  - type: web
    name: allermind-flutter-web
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./FLUTTER/Dockerfile
    dockerContext: ./FLUTTER
    envVars:
      - key: MODEL_SERVICE_URL
        value: http://allermind-model:10000
      - key: USER_PREFERENCE_SERVICE_URL
        value: http://allermind-userpreference:10000
    healthCheckPath: /

databases:
  # PostgreSQL Database (Managed Database)
  - name: allermind-db
    databaseName: allermind
    region: frankfurt
    ipAllowList: []
